In [13]:
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
sent = ['the glass of milk',
        'the glass of juice',
        'I am a good boy',
        'I am a game developer',
        'understand the meaning of words',
        'your videos are good']

In [15]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a game developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
voc_size = 100

### One hot Encoding

In [26]:
one_hot_rep = [one_hot(words, voc_size) for words in sent]
print(one_hot_rep)

[[35, 35, 82, 80], [35, 35, 82, 71], [82, 62, 49, 66, 88], [82, 62, 49, 32, 77], [87, 35, 86, 82, 23], [9, 74, 13, 66]]


### Embedding Representation

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np

In [29]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[ 0  0  0  0 35 35 82 80]
 [ 0  0  0  0 35 35 82 71]
 [ 0  0  0 82 62 49 66 88]
 [ 0  0  0 82 62 49 32 77]
 [ 0  0  0 87 35 86 82 23]
 [ 0  0  0  0  9 74 13 66]]


In [30]:
dim = 15

In [37]:
model = Sequential()
model.add(Embedding(1000,64))
model.compile(optimizer='adam', loss='mse')

In [38]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

# Sample sentences
sent = ['the glass of milk',
        'the glass of juice',
        'I am a good boy',
        'I am a game developer',
        'understand the meaning of words',
        'your videos are good']

# Vocabulary size
voc_size = 10000

# One-hot encoding
one_hot_rep = [one_hot(words, voc_size) for words in sent]
print("One-hot Encoded Representation:", one_hot_rep)

# Sentence length for padding
sent_length = 8

# Pad sequences to ensure uniform input length
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print("Padded Sequences:")
print(embedded_docs)

# Embedding dimensions
dim = 15

# Create embedding model
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

# Model summary
model.summary()

# Get the embedded representation
embedded_output = model.predict(embedded_docs)
print("Embedded Output Shape:", embedded_output.shape)


One-hot Encoded Representation: [[2807, 3698, 4933, 2753], [2807, 3698, 4933, 2051], [1072, 755, 8563, 9768, 3850], [1072, 755, 8563, 4784, 1166], [780, 2807, 6917, 4933, 617], [900, 1658, 8032, 9768]]
Padded Sequences:
[[   0    0    0    0 2807 3698 4933 2753]
 [   0    0    0    0 2807 3698 4933 2051]
 [   0    0    0 1072  755 8563 9768 3850]
 [   0    0    0 1072  755 8563 4784 1166]
 [   0    0    0  780 2807 6917 4933  617]
 [   0    0    0    0  900 1658 8032 9768]]


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
Embedded Output Shape: (6, 8, 15)
